# Generated by Django 3.2.23 on 2023-12-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bag',
            new_name='original_cart',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
    ]
